name: Build and Deploy Docs

on:
  push:
    branches:
      - master # Adjust this to the main branch name if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Adjust to the desired Node.js version

      - name: Install dependencies and build
        run: |
          yarn install
          yarn run build:react
          cd packages/docs
          yarn run docs:build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_DEPLOY }}
          publish_dir: ./packages/docs/.vitepress/dist # Adjust the path to the build output directory
