name: Build and Deploy Docs

on:
  push:
    branches:
      - docs/docusaurus # Adjust this to the main branch name if it's different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Adjust to the desired Node.js version

      - name: Install dependencies and build
        run: |
          cd ./core
          yarn install
          yarn run build
          cd ../


          yarn install
          yarn run build:react
          yarn run build:docusaurus

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_DEPLOY }}
          publish_dir: ./packages/docusaurus/build/ # Adjust the path to the build output directory
